### ISSUE TITLE
Aarch64 again

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#6]
I know it is not a big priority.
However you could spot something simple:

```text
[311/570] Building CXX object CMakeFiles/alizams.dir/common/structures.cpp.o
FAILED: CMakeFiles/alizams.dir/common/structures.cpp.o 
/usr/bin/c++ -DALIZA_GL_3_2_CORE -DDISABLE_SIMDMATH -DFORCE_PLATFORM_XCB -DITK_IO_FACTORY_REGISTER_MANAGER -DNDEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_WORKSTATION_MODE -I/run/build/alizams/ITKFactoryRegistration -I/run/build/alizams/mdcm/Source/Common -I/run/build/alizams/mdcm/Source/DataDictionary -I/run/build/alizams/mdcm/Source/DataStructureAndEncodingDefinition -I/run/build/alizams/mdcm/Source/MediaStorageAndFileFormat -I/run/build/alizams/mdcm/Utilities -I/run/build/alizams/mdcm/Utilities/mdcmcharls -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg/src/lib/openjp2 -I/run/build/alizams/mdcm/Utilities/mdcmzlib -I/run/build/alizams/mdcm/Utilities/mdcmuuid -I/run/build/alizams/b -I/run/build/alizams -I/run/build/alizams/common -I/run/build/alizams/GUI -I/run/build/alizams/dicom -isystem /app/include/ITK-5.2 -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtGui -isystem /usr/include/QtWidgets -isystem /usr/include/QtPrintSupport -isystem /usr/include/QtSvg -isystem /usr/include/QtSql -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer  -O2 -g -DNDEBUG -fPIC -MD -MT CMakeFiles/alizams.dir/common/structures.cpp.o -MF CMakeFiles/alizams.dir/common/structures.cpp.o.d -o CMakeFiles/alizams.dir/common/structures.cpp.o -c /run/build/alizams/common/structures.cpp
In file included from /run/build/alizams/common/structures.cpp:4:
/run/build/alizams/CG/glwidget-qt5-core.h:116:1: error: expected class-name before ‘{’ token
  116 | {
      | ^
/run/build/alizams/common/structures.cpp: In member function ‘void DisplayInterface::close(bool)’:
/run/build/alizams/common/structures.cpp:102:29: error: ‘class GLWidget’ has no member named ‘glDeleteTextures’
  102 |                         gl->glDeleteTextures(1, &cube_3dtex);
      |                             ^~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:136:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  136 |                                         gl->glDeleteVertexArrays(
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:138:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  138 |                                         gl->glDeleteBuffers(
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:151:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  151 |                                         gl->glDeleteVertexArrays(
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:153:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  153 |                                         gl->glDeleteBuffers(
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:166:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  166 |                                         gl->glDeleteVertexArrays(
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:168:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  168 |                                         gl->glDeleteBuffers(
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:217:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  217 |                                         gl->glDeleteVertexArrays(1, &(c->vaoid));
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:218:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  218 |                                         gl->glDeleteBuffers(1, &(c->vboid));
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:245:29: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  245 |                         gl->glDeleteVertexArrays(1, &(trimesh->qmesh->vaoid));
      |                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:246:29: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  246 |                         gl->glDeleteBuffers(2, trimesh->qmesh->vboid);
      |                             ^~~~~~~~~~~~~~~
[316/570] Building CXX object CMakeFiles/alizams.dir/main.cpp.o
FAILED: CMakeFiles/alizams.dir/main.cpp.o 
/usr/bin/c++ -DALIZA_GL_3_2_CORE -DDISABLE_SIMDMATH -DFORCE_PLATFORM_XCB -DITK_IO_FACTORY_REGISTER_MANAGER -DNDEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_WORKSTATION_MODE -I/run/build/alizams/ITKFactoryRegistration -I/run/build/alizams/mdcm/Source/Common -I/run/build/alizams/mdcm/Source/DataDictionary -I/run/build/alizams/mdcm/Source/DataStructureAndEncodingDefinition -I/run/build/alizams/mdcm/Source/MediaStorageAndFileFormat -I/run/build/alizams/mdcm/Utilities -I/run/build/alizams/mdcm/Utilities/mdcmcharls -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg/src/lib/openjp2 -I/run/build/alizams/mdcm/Utilities/mdcmzlib -I/run/build/alizams/mdcm/Utilities/mdcmuuid -I/run/build/alizams/b -I/run/build/alizams -I/run/build/alizams/common -I/run/build/alizams/GUI -I/run/build/alizams/dicom -isystem /app/include/ITK-5.2 -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtGui -isystem /usr/include/QtWidgets -isystem /usr/include/QtPrintSupport -isystem /usr/include/QtSvg -isystem /usr/include/QtSql -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer  -O2 -g -DNDEBUG -fPIC -MD -MT CMakeFiles/alizams.dir/main.cpp.o -MF CMakeFiles/alizams.dir/main.cpp.o.d -o CMakeFiles/alizams.dir/main.cpp.o -c /run/build/alizams/main.cpp
In file included from /run/build/alizams/main.cpp:10:
/run/build/alizams/CG/glwidget-qt5-core.h:116:1: error: expected class-name before ‘{’ token
  116 | {
      | ^
```

**Comment by issakomi** [comment]
I am not sure, maybe _-DALIZA_GL_3_2_CORE_ caused the error, i guess the option _ALIZA_QT5_COREGL_ was set to _ON_. I have tried just now to build with the option on Debian 10, x86_64 and it worked, but maybe the aarch64 system doesn't have OpenGL 3.2. Sorry, i don't have aarch64 hardware to test. Maybe it is worth to try without that option. I could look at CMakeCache.txt file (in build folder) to see cmake configuration.

**Comment by issakomi** [comment]
https://github.com/AlizaMedicalImaging/AlizaMS/blob/b99831db98bdb40d349dfa5cc7a82ea5486b845d/CMakeLists.txt#L582

Maybe to test set here to `find_package(OpenGL REQUIRED)`

In doubt probably skip for now _aarch64_ :(  it is "low reward", not much users will use it just now, but it may be important for future, i shall try to start supporting it little later.

**Comment by issakomi** [comment]
`find_package(OpenGL REQUIRED)`

I have set it and tagged version _v1.7.3_.

There is something wrong with OpenGL development environment, usually there are no need to care about, on Linux Qt devepment packages take it as dependency, on macOS it is in Xcode.

P.S. There are more changes, specially one is important, but only related to pure _Debug_ build. So there is no need to immediately update Fedora package, can wait. Maybe skipp for Fedora till next tag. Nothing critical.

**Comment by issakomi** [comment]
```
  - name: ITK
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DITK_LEGACY_REMOVE:BOOL=ON
      - -DITK_LEGACY_SILENT:BOOL=ON
      - -DBUILD_TESTING:BOOL=OFF
      - -DITK_WRAP_unsigned_short:BOOL=ON
      - -DITK_WRAP_rgb_unsigned_char:BOOL=OFF
      - -DITK_WRAP_rgba_unsigned_char:BOOL=OFF
      - -DITK_BUILD_DEFAULT_MODULES:BOOL=OFF
      - -DITKGroup_Core:BOOL=ON
      - -DITKGroup_Filtering:BOOL=ON
      - -DITKGroup_Segmentation:BOOL=ON
      - -DITKGroup_Nonunit:BOOL=ON
      - -DBUILD_EXAMPLES:BOOL=OFF
      - -DITK_USE_SYSTEM_ZLIB:BOOL=ON
      - -DITK_FORBID_DOWNLOADS=ON
```

BTW, i have never used ` -DITK_WRAP_unsigned_short:BOOL=ON` and other  ITK_WRAP_ options. Probably they are related to wrapping Python (BTW, IMHO other wraps don't work well with ITK 5).

```
      -DITK_LEGACY_REMOVE:BOOL=ON
      -DITK_LEGACY_SILENT:BOOL=ON
```
It is OK, as long it doesn't trigger warnings or errors, not required.


`-DITK_USE_SYSTEM_ZLIB:BOOL=ON`
If it works probably were not bad to use `-DMDCM_USE_SYSTEM_ZLIB:BOOL=ON` for AlizaMS build too.



The idea to use core OpenGL profile was not bad at all, it maybe better for _aarch64_. Sorry can not test, no aarch64 hardware.

**Comment by alcir** [comment]
Even with v1.7.3 I get the same 

```text
[299/554] Building CXX object CMakeFiles/alizams.dir/common/structures.cpp.o
FAILED: CMakeFiles/alizams.dir/common/structures.cpp.o 
/usr/bin/c++ -DDISABLE_SIMDMATH -DFORCE_PLATFORM_XCB -DITK_IO_FACTORY_REGISTER_MANAGER -DNDEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_WORKSTATION_MODE -I/run/build/alizams/ITKFactoryRegistration -I/run/build/alizams/mdcm/Source/Common -I/run/build/alizams/mdcm/Source/DataDictionary -I/run/build/alizams/mdcm/Source/DataStructureAndEncodingDefinition -I/run/build/alizams/mdcm/Source/MediaStorageAndFileFormat -I/run/build/alizams/mdcm/Utilities -I/run/build/alizams/mdcm/Utilities/mdcmcharls -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg/src/lib/openjp2 -I/run/build/alizams/mdcm/Utilities/mdcmuuid -I/run/build/alizams/b -I/run/build/alizams -I/run/build/alizams/common -I/run/build/alizams/GUI -I/run/build/alizams/dicom -isystem /app/include/ITK-5.2 -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtGui -isystem /usr/include/QtWidgets -isystem /usr/include/QtPrintSupport -isystem /usr/include/QtSvg -isystem /usr/include/QtSql -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer  -O2 -g -DNDEBUG -fPIC -std=c++14 -MD -MT CMakeFiles/alizams.dir/common/structures.cpp.o -MF CMakeFiles/alizams.dir/common/structures.cpp.o.d -o CMakeFiles/alizams.dir/common/structures.cpp.o -c /run/build/alizams/common/structures.cpp
In file included from /run/build/alizams/common/structures.cpp:6:
/run/build/alizams/CG/glwidget-qt5.h:112:1: error: expected class-name before ‘{’ token
  112 | {
      | ^
/run/build/alizams/common/structures.cpp: In member function ‘void DisplayInterface::close(bool)’:
/run/build/alizams/common/structures.cpp:102:29: error: ‘class GLWidget’ has no member named ‘glDeleteTextures’
  102 |                         gl->glDeleteTextures(1, &cube_3dtex);
      |                             ^~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:136:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  136 |                                         gl->glDeleteVertexArrays(
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:138:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  138 |                                         gl->glDeleteBuffers(
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:151:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  151 |                                         gl->glDeleteVertexArrays(
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:153:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  153 |                                         gl->glDeleteBuffers(
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:166:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  166 |                                         gl->glDeleteVertexArrays(
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:168:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  168 |                                         gl->glDeleteBuffers(
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:217:45: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  217 |                                         gl->glDeleteVertexArrays(1, &(c->vaoid));
      |                                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:218:45: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  218 |                                         gl->glDeleteBuffers(1, &(c->vboid));
      |                                             ^~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:245:29: error: ‘class GLWidget’ has no member named ‘glDeleteVertexArrays’
  245 |                         gl->glDeleteVertexArrays(1, &(trimesh->qmesh->vaoid));
      |                             ^~~~~~~~~~~~~~~~~~~~
/run/build/alizams/common/structures.cpp:246:29: error: ‘class GLWidget’ has no member named ‘glDeleteBuffers’
  246 |                         gl->glDeleteBuffers(2, trimesh->qmesh->vboid);
      |                             ^~~~~~~~~~~~~~~
[304/554] Building CXX object CMakeFiles/alizams.dir/main.cpp.o
FAILED: CMakeFiles/alizams.dir/main.cpp.o 
/usr/bin/c++ -DDISABLE_SIMDMATH -DFORCE_PLATFORM_XCB -DITK_IO_FACTORY_REGISTER_MANAGER -DNDEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_WORKSTATION_MODE -I/run/build/alizams/ITKFactoryRegistration -I/run/build/alizams/mdcm/Source/Common -I/run/build/alizams/mdcm/Source/DataDictionary -I/run/build/alizams/mdcm/Source/DataStructureAndEncodingDefinition -I/run/build/alizams/mdcm/Source/MediaStorageAndFileFormat -I/run/build/alizams/mdcm/Utilities -I/run/build/alizams/mdcm/Utilities/mdcmcharls -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg -I/run/build/alizams/mdcm/Utilities/mdcmopenjpeg/src/lib/openjp2 -I/run/build/alizams/mdcm/Utilities/mdcmuuid -I/run/build/alizams/b -I/run/build/alizams -I/run/build/alizams/common -I/run/build/alizams/GUI -I/run/build/alizams/dicom -isystem /app/include/ITK-5.2 -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtGui -isystem /usr/include/QtWidgets -isystem /usr/include/QtPrintSupport -isystem /usr/include/QtSvg -isystem /usr/include/QtSql -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer  -O2 -g -DNDEBUG -fPIC -std=c++14 -MD -MT CMakeFiles/alizams.dir/main.cpp.o -MF CMakeFiles/alizams.dir/main.cpp.o.d -o CMakeFiles/alizams.dir/main.cpp.o -c /run/build/alizams/main.cpp
In file included from /run/build/alizams/main.cpp:12:
/run/build/alizams/CG/glwidget-qt5.h:112:1: error: expected class-name before ‘{’ token
  112 | {
      | ^
ninja: build stopped: subcommand failed.
Error: module alizams: Child process exited with code 1
```

But I understand that it is difficult to investigate if you don't have aarch64 hardware.
I will see if it is possible to exclude such architecture on flathub.

**Comment by issakomi** [comment]
Thank you. Not sure why the error happens, OpenGL seems to be available, otherwise cmake would fail with "required". Maybe Qt is build somehow with different options. AFAIK on Fedora aarch64 works. Yes, probably better just exclude is OK.

**Comment by alcir** [comment]
> Maybe you could update to v1.7.3 and let the build for _aarch64_ run once again to see the logs. I have to admit that i don't 

Yes, the last log is using 1.7.3

**Comment by issakomi** [comment]
I have moved the tag ca. 30 min after the 1st attempt (sorry, bad practice), found out that last commit was not in, but even if, the change was that "requried" thingy, it will not really help. Thank you very much!

**Comment by alcir** [comment]
> I have moved the tag ca. 30 min after the 1st attempt (sorry, bad practice), found out that last commit was not in, but even if, the change was that "required" thingy, it will not really help. Thank you very much!

Oh. I mean that such log is from a local build.

**Comment by issakomi** [comment]
`/run/build/alizams/CG/glwidget-qt5.h:112:1: error: expected class-name before ‘{’ token`

It is here `class GLWidget : public QOpenGLWidget, public QOpenGLFunctions_3_0`

Looks like _QOpenGLWidget_ or _QOpenGLFunctions_ class is not available, probably Qt was compiled without (--no-opengl), not 100% sure, but don't have an idea how to help. Sorry.

**Comment by alcir** [comment]
Looking here, if it is the right place, https://github.com/KDE/flatpak-kde-runtime/blob/a635bbeddbec37fcc3e35484636f0f549798d2bb/org.kde.Sdk.json.in#L114
`qt5-qtbase` is compiled with `-opengl es2`, does it could matter?

**Comment by issakomi** [comment]
Yes, it does. It is the reason. Can not work.

**Comment by alcir** [comment]
Thanks.

**Comment by alcir** [comment]
This is interesting https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/19

**Comment by issakomi** [comment]
Thank you.
